apiVersion: v1
kind: ServiceAccount
metadata:
  name: merge-sort
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: merge-sort
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: merge-sort
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: merge-sort
subjects:
- kind: ServiceAccount
  name: merge-sort
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: merge-sort
spec:
  template:
    spec:
      serviceAccountName: merge-sort
      restartPolicy: Never
      containers:
      - image: busybox
        name: main
        command: ["/bin/sh"]
        args: ["-c", "date"]
---