# https://github.com/aevea/action-kaniko
name: Kaniko build
on:
  push:
    branches:
      - "main"
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: bazhova/merge-sort
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
          cache_registry: bazhova/merge-sort
          tag_with_latest: true
